env: "prod"
storage_type: "memory" # "postgres" или "memory"
storage_path: "postgres://postgres:123@postgres:5432/urlshortener?sslmode=disable"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s