env: "prod"
storage_type: "postgres"  # "postgres" или "memory"
storage_path: "postgres://postgres:123@localhost:5432/urlshortener?sslmode=disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s